version: 0.2
env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "{{s3_bucket_url}}"
        BUILD_FOLDER: "dist"

APP_NAME: "Hello World"

phases:
    install:
        runtime-versions:
        nodejs: 14

    pre_build:
        commands:
            - echo installing dependencies...
            - npm i -g @angular/cli
            - npm install

    build:
        commands:
            - echo Build started
            - ng build 

    post_build:
        commands:
        - aws s3 cp dist s3://${S3_BUCKET} --recursive
        - echo Build completed on `date`

artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes