version: 0.2
env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "{{s3_bucket_url}}"
        BUILD_FOLDER: "dist"
        BUILD_ENV: "prod"

phases:
    install:
        commands:
            - echo installing dependencies...
            - npm i -g @angular/cli
            - npm install

    build:
        commands:
            - echo Build started on `date`
            - ng build --${BUILD_ENV}

    post_build:
        commands:
        - aws s3 cp dist s3://arn:aws:s3:::helloworld-server/ --recursive
        - echo Build completed on `date`

artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes