version: 0.2
env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "{{s3_bucket_url}}"
        BUILD_FOLDER: "dist"
        BUILD_ENV: "prod"

phases:
    install:
        runtime-versions:
            nodejs: 14
        commands:
            - echo installing dependencies...
            - npm i -g @angular/cli
            - npm install

    build:
        commands:
            - echo Build started on `date`
            - ng build --${BUILD_ENV}

artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes